extraction:
  cpp:
    after_prepare: 
      - python report.py 26
  cobol:
    after_prepare: 
      - python report.py 26
  csharp:
    after_prepare: 
      - python report.py 26
  java:
    after_prepare: 
      - python report.py 26
  javascript:
    after_prepare: 
      - python report.py 26
  python:
    after_prepare: 
      - python report.py 26
